name: Vvflow CI

on: pull_request

jobs:
  build-ubuntu-bionic:
    runs-on: ubuntu-18.04
    env:
      APT_PACKAGES: liblapack-dev gnuplot
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get install ${APT_PACKAGES}
        pip3 install -r pytest/requirements.txt

    - name: Cache CMakeFiles
      uses: actions/cache@v2
      with:
        path: |
          build
          ~build/deb
        key: bionic-cmake-cache-01

    - name: Build & Test
      run: |
        mkdir -p build
        pushd build
        cmake ..
        make -j
        ctest -VV
        cpack
        popd

    - name: Upload to packagecloud/nightly
      if: github.ref == 'refs/heads/master'
      run: >
        curl
        -u "${{ secrets.PACKAGECLOUD_TOKEN }}:"
        -F "package[distro_version_id]=190"
        -F "package[package_file]=@$(ls build/deb/vvflow-*.deb | head -n1)"
        -v https://packagecloud.io/api/v1/repos/vvflow/nightly/packages.json
